# Site settings 配置站点
title: 'LIYI的博客'
description: ''
keyword: 'LIYI的博客, javascript, vue, vuejs, 小程序, 前端, 日志，前端开发, 前端博客, 设计'
url: 'https://smme.cc'

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2017

# Author
author: 'LIYI'
nickname: 'VoLi'
bio: '做更好的自己'
avatar: '/assets/img/profile.png'
github_username: XiaoLiz

# Search
search: true

# Night mode
nightMode: false

# Comments 评论功能
comments:
  disqus: false
  disqus_url: 'https://smme.disqus.com/embed.js'

# MathJax 公式支持 by Ray-Eldath
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站
# url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
   github: '//github.com/XiaoLiz/'
#  weibo: '//weibo.com/lovecolcol'
#  juejin: '//juejin.im/user/57a6f434165abd006159b4cc'
#  instagram: '//www.instagram.com/steveliaocn'
#  github: '//github.com/kaeyleo'

# Tags 设置标签
recommend-tags: true 
recommend-condition-size: 12

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: false

# Permalink
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
